version: '3.8'
services:
  api:
    build: ./api
    command: ./bin/dev
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./api:/api"
    tty: true

  webapp:
    image: node:16
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - "./webapp:/webapp"
    working_dir: /webapp
    command: sh -c "npm install && npm start"
    tty: true
