services:
  app:
    build: .
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - "./:/app"
    command: rails server -b 0.0.0.0
    depends_on:
      - tailwind

  tailwind:
    build: .
    volumes:
      - "./:/app"
    command: rails tailwindcss:watch
    stdin_open: true
